Algoritmo "semnome"
// Disciplina   : UC3 ALGORITIMOS
// Professor   : Mateus de Paula Pereira 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 20/05/2025
Var
// Seção de Declarações das variáveis 
      dinheiro: real
      dolar: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

   escreva ("Dinheiro em reais: ")
   leia (dinheiro)
   
   dolar <- dinheiro / 3.45

   escreva ("Quantidade de dolar:",dolar," dolar")
   

Fimalgoritmo