Algoritmo "semnome"
// Disciplina   : UC3 ALGORITIMOS
// Professor   : Mateus de Paula Pereira 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 19/05/2025
Var
// Seção de Declarações das variáveis 

nome: caracter

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

//EXERCICIO 2

   escreva ("Qual é seu nome? ")
   leia (nome)

   escreva ("Olá ", nome," é um prazer te conhecer!")

Fimalgoritmo