Algoritmo "semnome"
// Disciplina   : UC3 ALGORITIMOS
// Professor   : Mateus de Paula Pereira 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 21/05/2025
Var
// Seção de Declarações das variáveis 

   largura: real
   altura: real
   metros: real
   litros: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

     escreva ("Qual a ALTURA da parede? ")
     leia (altura)

     escreva ("Qual a LARGURA da parede? ")
     leia (largura)
     
     metros <- altura * largura
     
     escreval ("A parede tem ",metros," metros quadrados.")
     
     litros <- metros /2
     
     escreval ("A parede vai precisar aproximadamente de: ",litros," litros de tinta.")
     


Fimalgoritmo