Algoritmo "semnome"
// Disciplina   : UC3 ALGORITIMOS
// Professor   : Mateus de Paula Pereira 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 21/05/2025
Var
// Seção de Declarações das variáveis 

   dias: inteiro
   horas, total: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

    escreva ("Dias trabalhados em um mês: ")
    leia (dias)
    
    horas <- dias * 8
    
    total <- horas * 25
    
    escreva ("Salário total de um funcionario que trabalha ",horas," é:R$ ",total)

Fimalgoritmo