Algoritmo "semnome"
// Disciplina   : UC3 ALGORITIMOS
// Professor   : Mateus de Paula Pereira 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 19/05/2025
Var
// Seção de Declarações das variáveis 

numero, dobro, terca: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

   escreva ("Digite um numero: ")
   leia (numero)
   
   dobro <- numero *2
   terca <- numero /3
   
   escreva ("O dobro é: ",dobro, "| A terça parte é: ",terca)

Fimalgoritmo