Algoritmo "semnome"
// Disciplina   : UC3 ALGORITIMOS
// Professor   : Mateus de Paula Pereira 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 20/05/2025
Var
// Seção de Declarações das variáveis 

   idade: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

     escreva ("digitr sua idade ")
     leia (idade)

     se (idade >= 18) então
     escreva ("você é maior de idade.")

     senao
     escreva ("você é menor de idade.")
     fimse

Fimalgoritmo