Algoritmo "semnome"
// Disciplina   : UC3 ALGORITIMOS
// Professor   : Mateus de Paula Pereira 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 19/05/2025
Var
// Seção de Declarações das variáveis 

nome: caracter
numero: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

 escreva ("Nome do funcionario(a): ")
     leia (nome)

     escreva ("Salário: ")
     leia (numero)

     escreva ("O funcionario(a) ",nome," tem um salário de",numero," em junho")


Fimalgoritmo