Algoritmo "semnome"
// Disciplina   : UC3 ALGORITIMOS
// Professor   : Mateus de Paula Pereira 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 19/05/2025
Var
// Seção de Declarações das variáveis 

numero: real
resultado1, resultado2: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
       escreva ("Digite um numero: ")
       leia (numero)
       
       resultado1 <- numero -1
       
       resultado2 <- numero +1
       
       escreva ("O Antecessor é: ",resultado1, " | O Sucessor é: ",resultado2)

       //6:2
Fimalgoritmo