Algoritmo "semnome"
// Disciplina   : UC3 ALGORITIMOS
// Professor   : Mateus de Paula Pereira 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 19/05/2025
Var
// Seção de Declarações das variáveis 

   a: real
   b: real
   resultado
   
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

   escreva ("Digite um valor: ")
   leia (a)
   
   escreva ("Digite outro valor: ")
   leia (b)
   
   soma <- a + b
   
   escreva ("resultado da soma: ",soma)


Fimalgoritmo