Algoritmo "semnome"
// Disciplina   : UC3 ALGORITIMOS
// Professor   : Mateus de Paula Pereira 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 19/05/2025
Var
// Seção de Declarações das variáveis 

   nome: caracter
   nota1: real
   nota2: real
   media: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

   escreva ("Escreva o nome do(a) aluno(a): ")
   leia (nome)
   
   escreva ("Nota 1: ")
   leia (nota1)
   
   escreva ("Nota 2: ")
   leia (nota2)
   
   media <- (nota1 + nota2) /2
   
   escreva ("resultado da media de ",nome," é: ",media)
   
   
Fimalgoritmo