Algoritmo "semnome"
// Disciplina   : UC3 ALGORITIMOS
// Professor   : Mateus de Paula Pereira 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 21/05/2025
Var
// Seção de Declarações das variáveis 

   A, B, C, Delta: real
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

        escreva ("Valor de A: ")
        leia (A)
        
        escreva ("Valor de B: ")
        leia (B)
        
        escreva ("Valor de C: ")
        leia (C)
        
        Delta <- B^2 -4 *A*C

        escreva ("O valor de Delta é: ",Delta)

Fimalgoritmo