Algoritmo "semnome"
// Disciplina   : UC3 ALGORITIMOS
// Professor   : Mateus de Paula Pereira 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 19/05/2025
Var
// Seção de Declarações das variáveis 

   nome: caracter
   numero: real
   a: real
   b: real
   resultado: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

   escreva ("Valor 1: ")
   leia (a)
   
   escreva ("Valor 2: ")
   leia (b)
   
   resultado <- a + b
   escreva ("resultado é = " ,resultado)
   

//EXERCICIO 2

   escreva ("Qual é seu nome? ")
   leia (nome)
   
   escreva ("Olá ", nome," é um prazer te conhecer!")
   
//EXERCICIO 3

     escreva ("Nome do funcionario(a): ")
     leia (nome)
     
     escreva ("Salário: ")
     leia (numero)
     
     escreva ("O funcionario(a) ",nome," tem um salário de ",numero," em junho")
     
// EERCICIO 4
      
Fimalgoritmo