Algoritmo "semnome"
// Disciplina   : UC3 ALGORITIMOS
// Professor   : Mateus de Paula Pereira 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 21/05/2025
Var
// Seção de Declarações das variáveis 

     salario: real
     aumento: real
     novo: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

    escreva ("Valor do sálario:R$ ")
    leia (salario)
    
    aumento <- salario * 0.15
    escreval ("valor do desconto:",aumento)
    
    novo <- salario + aumento
    escreva ("O novo salário com 15% de aumento valerá: R$ ",novo)

Fimalgoritmo